version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:5000
    volumes:
      - ./:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.docker.env
  redis:
    image: redis:alpine
    ports:
      - 6379:6379